"""add description column

Revision ID: 38dc1542ec9d
Revises: 17bcecb63ad5
Create Date: 2025-11-09 13:06:18.877414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38dc1542ec9d'
down_revision: Union[str, Sequence[str], None] = '17bcecb63ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_records', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection_records', 'description')
    # ### end Alembic commands ###
