"""create detection record table

Revision ID: f74702cf63da
Revises: 38dc1542ec9d
Create Date: 2025-11-09 13:22:58.629194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74702cf63da'
down_revision: Union[str, Sequence[str], None] = '38dc1542ec9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_records_id'), table_name='detection_records')
    op.drop_table('detection_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(), nullable=True),
    sa.Column('result_json', sa.TEXT(), nullable=True),
    sa.Column('alert', sa.BOOLEAN(), nullable=True),
    sa.Column('acknowledge', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_records_id'), 'detection_records', ['id'], unique=False)
    # ### end Alembic commands ###
